# Generated by Django 2.2.7 on 2025-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20180727_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'По алфавиту'), ('none', 'Как добавлены')], default='none', help_text='Порядок, в котором отображаются варианты ответов', max_length=30, null=True, verbose_name='Порядок ответов'),
        ),
    ]
